### PR TITLE
Ob fix

### PR DESCRIPTION
**Pull request by michield**
Sorry, didn't mean to add to the PR. It's a bit annoying how the workflow does that. I meant to create a new one.

### CODE REVIEW

**Comment by bramley** [comment]
You need to use a separate local branch for each change. Then push that branch and raise the pull request against that. This one does seem to be a branch, but the first one wasn't.

**Comment by michield** [comment]
ok, I'll make sure to branch first before editing

**Comment by bramley** [comment]
Again, I'd like an explanation of why this change is needed. I had to go looking for the definition of cl_output() to find what it does, and still don't really see what the problem is.

**Comment by michield** [comment]
the problem was that you end ob_ and then don't start it again. As a result, there was undesired output on the commandline. cl_output deals with that.

**Pull request closed without merging**
