### PR TITLE
Add the ability to use [RSS:N_ITEMS] in the subject of the email

### PR DESCRIPTION
**Pull request by talgalili**
This diff enable us to create a newsletter that says in the subject how many RSS items are in the email, using the new [RSS:N_ITEMS] placeholder.

E.g.:
`This e-mail has [RSS:N_ITEMS] new posts for you (e.g.: [RSSITEM:TITLE] )`

### CODE REVIEW

**Comment by bramley** [comment]
I was also looking at this. Your original example showed something like "and 5 more articles" which is N - 1 not N.

When you use the RSSITEM: TITLE placeholder there is already the ability to add some text  such as "and more" when there is more than one item to include. I was thinking that the N or N - 1 would go in that additional text, not within the subject as a whole, although both could be useful.

**Comment by talgalili** [comment]
Thanks.
I have another version internally with the n-1, and wasn't sure of to
include it or not.
I can paste the code here later today.
The issue is that if there is only 1 post in some day, it would say there
are 0 more posts (which is not that useful).

It's possible to do a conditional placeholder, but I wasn't sure people
here would want anyway, if you're happy with accepting this commit, it
would be great.
If you want me to also add the conditional n-1 items text, I can add it.

WDYT?

**Comment by bramley** [comment]
> The issue is that if there is only 1 post in some day, it would say there
> are 0 more posts (which is not that useful).

That is the reason for the current processing which appends text only when there is more than one item.

I think that having two placeholders for N and N - 1 is simple enough to understand. The N placeholder can be in the subject or the additional text, the N -1 makes sense only in the additional text.
I don't really want to have conditional placeholders.

No need to paste any further code as I have my own branch under development.

**Comment by bramley** [comment]
I have incorporated this change into the development branch that you installed yesterday. Can you update the plugin in phplist to test it, along with the latest TOC changes. Once it is ok, I will make a proper release.

You can now include these placeholders in the subject and the additional text
[RSS:N] and [RSS:N-1]

**Comment by talgalili** [comment]
Just tested, I can confirm it works.
Thanks for being so fast and responsive!

I'm closing this PR, since you've already added it on your own branch.

**Comment by talgalili** [comment]
cc:
This will resolve #29

**Pull request closed without merging**
