### PR TITLE
add cronjob setting

### PR DESCRIPTION
**Pull request by michield**
the core has (will have) a method for plugins to setup cronjobs that will be called on regular intervals. This setting sets it for this plugin.

### CODE REVIEW

**Comment by bramley** [comment]
Is the new cron job processing explained anywhere?  Is this meant to be similar to the remote queue processing? I don't quite see why it is called a cron job (which has a specific, well-understood meaning).

Announcing the new feature, along with the documentation url (which I also wasn't aware of), could be done through the dev mailing list.

**Comment by bramley** [comment]
I'm not sure that the "get" page should run in the way that the new feature will work. Or at least make it a configurable option for the administrator. In the guidance notes I recommended running the page immediately prior to processing the message queue.

As I mentioned earlier, I am not sure "$cronjob" is the right term. Perhaps $periodicTask or just $task. 
The problem that you identify with processqueue and processbounces of using the same function names can also apply to plugins. The code that is included for each plugins page is in global scope and, without any naming restrictions, variable and function names can clash.

Perhaps a more reliable way is to invoke a method from each plugin. Then the plugin developer has the responsibility to structure the code so that it can be run as a separate page or through a method call.

**Comment by michield** [comment]
Well, cronjob is now a common term for this, particularly in relation to phpList. I agree that running it as a method is nicer. I had another patch that pulled the "get" function into the plugin class, but decided to leave that for now, in order not to convolute the PR. It can be easily extended by allowing a "method" call in the setup, instead of a "page" one as it is now.

It would be nice to add the option to manage the frequency in the UI, but for now, doing it like this is fine. It can add the logic to search for RSS campaigns, and find their frequency, and it can also be extended to have a "firstrun" in the cronJob setting, which can also be calculated. That way you can achieve the "just before sending" effect you're after. 

I was out to create a generic extensible way to easily allow recurring events in plugins.

**Comment by bramley** [comment]
What I would like people to do is raise an issue first so that the problem/issue/enhancement can be discussed. I'm not going to apply pull requests without understanding their background and probably will want to implement the change myself instead of applying a pull request.
I'm still not convinced that sequentially including "pages" from several plugins is a good idea. Using a callable http://php.net/manual/en/language.types.callable.php will allow several ways of specifying the function

```
'callback' => array($this, 'getRss'),  // instance method
'callback' => 'RssFeedPlugin::getRss', // static method
```

Also, whether the plugin developer should define the frequency and timing of processing.

**Pull request closed without merging**
